### ISSUE TITLE
[TRAC] Two code issues

### ISSUE THREAD

**Issue by qtothec** [coin-or/Clp.old#11]
Moved from TRAC as part of COIN fORgery: https://projects.coin-or.org/Clp/ticket/67

![snip](https://user-images.githubusercontent.com/5910700/47045273-6cf71d80-d160-11e8-93fd-de22c05a8943.PNG)

Hi,

the static analyzer of clang-3.5 found two issues in your code that I want to mention here because they are bugs.

There are two occurrences of "a = a" assignments in the Clp code base. I think the attached diff-like files fix them. However, I am not sure if the second one is the right way to go.

Regards, Stephan

**Comment by sbeyer** [comment]
The diff is available here: https://projects.coin-or.org/Clp/attachment/ticket/67/gjkh

I can also make a pull request on GitHub if the issue is still present.

**Comment by jjhforrest** [comment]
Already in trunk
