### ISSUE TITLE
[TRAC] add a method to use CbcOrClpParam in ClpSimplex

### ISSUE THREAD

**Issue by qtothec** [coin-or/Clp.old#26]
Moved from TRAC as part of COIN fORgery: https://projects.coin-or.org/Clp/ticket/61

Today, it's not possible to use CbcOrClpParams? in ClpSimplex?. A method which can set these options in ClpSimplex? should be great. These options are only usable in ClpMain? ...

**Comment by jjhforrest** [comment]
See driver3 in examples
