### ISSUE TITLE
[TRAC] Cbc-infeasible Cplex&GLPK-feasible

### ISSUE THREAD

**Issue by qtothec** [coin-or/Clp.old#28]
Moved from TRAC as part of COIN fORgery: https://projects.coin-or.org/Clp/ticket/70

Hello all,

I’m having issues solving my model with Cbc. . GLPK and Cplex find feasible solutions. Cplex finds the optimal solution within a minute, while GLPK needs several hours to find a decent solution.

Cbc results:

Continuous objective value is 122787 - 0.61 seconds Cgl0003I 7 fixed, 0 tightened bounds, 321 strengthened rows, 0 substitutions Cgl0000I Cut generators found to be infeasible! (or unbounded) Pre-processing says infeasible or unbounded

When setting the parameters presolve and preprocess to off, Cbc (sometimes) finds an optimal solution with objective value 480069. However, the solution provided by Cplex is 300274.

Do you know why cbc fails to solve this problem to optimality?

**Comment by bernalde** [comment]
Attachment:
https://projects.coin-or.org/Clp/attachment/ticket/70/Allocation.mps

**Comment by jjhforrest** [comment]
Seems OK with trunk - just a few seconds
