### ISSUE TITLE
[TRAC] OsiClpSolverInterface.cpp:7453: bad if test ?

### ISSUE THREAD

**Issue by bernalde** [coin-or/Clp.old#30]
Moved from TRAC as part of COIN fORgery: https://projects.coin-or.org/Clp/ticket/76
![image](https://user-images.githubusercontent.com/8647329/47046224-aaf54100-d162-11e8-8b89-7104b2a65ebc.png)
OsiClpSolverInterface?.cpp:7453:24: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op] 
Source code is 
```
if (array[0]>=0,
array[0]<=2)
```
 Maybe better code 
`if (array[0] >= 0 && array[0] <= 2) `

**Comment by jjhforrest** [comment]
Correct - modified (had been modified to || not &&)
