### ISSUE TITLE
[TRAC] Unbounded ray not found when there are no constraint

### ISSUE THREAD

**Issue by bernalde** [coin-or/Clp.old#49]
Moved from TRAC as part of COIN fORgery:
![image](https://user-images.githubusercontent.com/8647329/47047163-ded16600-d164-11e8-88a7-fa02b21ef9e2.png)

Dear Clp maintainers,

For the trivial problem (see attachment for an mps):

Minimize x0 + x1 Subject To

Bounds

x1 >= 0 x1 free

End

Clp correctly detects it to be unbounded but returns NULL when asked for the Unbounded ray (see ​here https://github.com/JuliaOpt/Clp.jl/pull/20).

While it may look silly to ask Clp to solve such a trivial problem, this actually happens as part of a larger algorithms (see ​here https://github.com/blegat/StochasticDualDynamicProgramming.jl) so it wasn't generated by hand and the fact that Clp fails on such simple problems makes it unusable for the whole algorithm :(

Attachment: https://projects.coin-or.org/Clp/attachment/ticket/82/ticket82.mps
Trivial unbounded problem for which the unbounded ray is not found

**Comment by jjhforrest** [comment]
Occurs when no rows as code exits very early - hopefully fixed in trunk
